export const GET_EMAIL_SCHEMA = '@@EMAIL/GET_SCHEMA';
export const SAVE_EMAIL_SCHEMA = '@@EMAIL/SAVE_VALUES';

export const GET_NOTIFICATION_SCHEMA = '@@NOTIFICATION/GET_SCHEMA';
export const GET_NOTIFICATION_SCHEMAS = '@@NOTIFICATION/GET_SCHEMAS';
export const SAVE_NOTIFICATION_SCHEMA = '@@NOTIFICATION/SAVE_VALUES';

export const ACTION_TYPES = ['_PENDING', '_FULFILLED', '_REJECTED'].reduce(
  (acc, curr) => ({
    ...acc,
    ...{
      [`${GET_EMAIL_SCHEMA}${curr}`]: GET_EMAIL_SCHEMA,
      [`${SAVE_EMAIL_SCHEMA}${curr}`]: SAVE_EMAIL_SCHEMA,
      [`${GET_NOTIFICATION_SCHEMA}${curr}`]: GET_NOTIFICATION_SCHEMA,
      [`${SAVE_NOTIFICATION_SCHEMA}${curr}`]: SAVE_NOTIFICATION_SCHEMA,
    },
  }),
  {
    GET_EMAIL_SCHEMA,
    SAVE_EMAIL_SCHEMA,
    GET_NOTIFICATION_SCHEMA,
    GET_NOTIFICATION_SCHEMAS,
    SAVE_NOTIFICATION_SCHEMA,
  }
);
